name: Deploy to aws

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: develop
    permissions:
      id-token: write
      contents: read
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
    steps:
      
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Prerequisite Installation
        run: |
          sudo npm install -g aws-cdk
          cdk --version

      - name: Install dependencies
        run: |
          cd deploy
          npm install
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ROLE }}

      - name: Deploy SSPApigatewayStack
        run: |
          cd deploy
          cdk deploy --require-approval never SSPApigatewayStack --debug --trace

      - name: Deploy SSPSupabaseSecretStack
        run: |
          cd deploy
          cdk deploy --require-approval never SSPSupabaseSecretStack --debug --trace

      - name: Deploy SSPRolesStack
        run: |
          cd deploy
          cdk deploy --require-approval never SSPRolesStack --debug --trace